#!/usr/bin/env bash

# default config
destination="/dxdir"
extras=()

exit_with_usage () {
  cat << USAGE
Usage
    `basename $0` [-hs][-i <image>][-p <port>] <command>

Options
    -h          show usage info
    -i <image>  specify a docker image to use (e.g. node:lts-alpine)
    -p <port>   specify port binding (as host:guest) for docker (e.g. 5000:80)
    -s          launch an interactive shell

Examples
    `basename $0` npx cowsay hello
    `basename $0` bundle exec rails c
    `basename $0` youtube-dl https://youtu.be/LfhkoCAK6aA
    `basename $0` -i node:lts-alpine npm init
    `basename $0` -p 5000:5000 npx serve .
    `basename $0` -s ruby script.rb
USAGE
  exit 0
}

while getopts ':hips' opt
do
  case $opt in
    h)
      exit_with_usage
      ;;
    i)
      shift
      image="$1"
      shift
      ;;
    p)
      shift
      extras+=( "-p" "$1" )
      shift
      ;;
    s)
      shift
      shell=1
      ;;
  esac
done

# handle commands
command="$1"

# show usage if no command is supplied
if [ -z "$command" ]
then
  exit_with_usage
fi

# if no image is supplied, look for one that is supported
if [ -z "$image" ]
then
  # deno
  if [[ " deno " =~ " $command " ]]
  then
    image="hayd/deno:alpine"
    destination="/app"

    # the entrypoint is already set for this image
    shift
  fi

  # ffmpeg
  if [[ " ffmpeg " =~ " $command " ]]
  then
    image="jrottenberg/ffmpeg:alpine"

    # the entrypoint is already set for this image
    shift
  fi

  # node
  if [[ " node npm npx yarn " =~ " $command " ]]
  then
    image="node:lts-alpine"
  fi

  # php
  if [[ " php composer " =~ " $command " ]]
  then
    image="composer:2"
  fi

  # python
  if [[ " python pip " =~ " $command " ]]
  then
    image="python:alpine"
  fi

  # ruby
  if [[ " ruby bundle bundler gem irb " =~ " $command " ]]
  then
    image="ruby:2-alpine"
  fi

  # rust
  if [[ " cargo " =~ " $command " ]]
  then
    image="rust:alpine"
  fi

  # youtube-dl
  if [[ " youtube-dl " =~ " $command " ]]
  then
    # https://github.com/Jeeaaasus/youtube-dl
    image="jeeaaasustest/youtube-dl:latest"
    destination="/downloads"
  fi

  # command is not yet supported
  if [ -z "$image" ]
  then
    echo "Command '$command' is not yet supported. Consider opening an Issue or Pull Request at https://github.com/voraciousdev/dx if you think it should be added."
    exit 0
  fi
fi

# run the command
if [ -z "$shell" ]
then
  docker run -it --rm -v `pwd`:"$destination" -w "$destination" "${extras[@]}" "$image" "$@"
else
  docker run -it --rm -v `pwd`:"$destination" -w "$destination" "${extras[@]}" --entrypoint sh "$image"
fi
